In [2]:
!pip install nltk scikit-learn gensim

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 51.2 MB/s eta 0:00:00


In [3]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [4]:
documents = [
    "I love natural language processing",
    "Natural language processing is fun",
    "I love machine learning",
    "Machine learning is powerful"
]


In [5]:
import nltk
nltk.download('punkt_tab')

from nltk.tokenize import word_tokenize

tokenized_docs = [word_tokenize(doc.lower()) for doc in documents]
print(tokenized_docs)

[['i', 'love', 'natural', 'language', 'processing'], ['natural', 'language', 'processing', 'is', 'fun'], ['i', 'love', 'machine', 'learning'], ['machine', 'learning', 'is', 'powerful']]


[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


In [6]:
# # Bag of Words – Count Occurrence
# Bag of Words represents text as a vector of word frequencies, ignoring grammar and word order.

In [7]:
from collections import Counter

bow_counts = [Counter(doc) for doc in tokenized_docs]
bow_counts


[Counter({'i': 1, 'love': 1, 'natural': 1, 'language': 1, 'processing': 1}),
 Counter({'natural': 1, 'language': 1, 'processing': 1, 'is': 1, 'fun': 1}),
 Counter({'i': 1, 'love': 1, 'machine': 1, 'learning': 1}),
 Counter({'machine': 1, 'learning': 1, 'is': 1, 'powerful': 1})]

In [8]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()
X_counts = vectorizer.fit_transform(documents)

print("Vocabulary:", vectorizer.get_feature_names_out())
print(X_counts.toarray())


Vocabulary: ['fun' 'is' 'language' 'learning' 'love' 'machine' 'natural' 'powerful'
 'processing']
[[0 0 1 0 1 0 1 0 1]
 [1 1 1 0 0 0 1 0 1]
 [0 0 0 1 1 1 0 0 0]
 [0 1 0 1 0 1 0 1 0]]


In [13]:
# TF-IDF
from sklearn.feature_extraction.text import TfidfVectorizer

In [14]:
tfidf_vectorizer = TfidfVectorizer()
X_tfidf = tfidf_vectorizer.fit_transform(documents)

print("Features:")
print(tfidf_vectorizer.get_feature_names_out())

print("\nTF-IDF Matrix:")
print(X_tfidf.toarray())


Features:
['fun' 'is' 'language' 'learning' 'love' 'machine' 'natural' 'powerful'
 'processing']

TF-IDF Matrix:
[[0.         0.         0.5        0.         0.5        0.
  0.5        0.         0.5       ]
 [0.53556627 0.4222466  0.4222466  0.         0.         0.
  0.4222466  0.         0.4222466 ]
 [0.         0.         0.         0.57735027 0.57735027 0.57735027
  0.         0.         0.        ]
 [0.         0.46580855 0.         0.46580855 0.         0.46580855
  0.         0.59081908 0.        ]]


In [16]:
# Word2Vec Embeddings
from gensim.models import Word2Vec

In [17]:
word2vec_model = Word2Vec(
    sentences=tokenized_docs,
    vector_size=100,
    window=5,
    min_count=1,
    workers=4
)


In [18]:

# get vector for word
vector = word2vec_model.wv["language"]
print("Vector length:", len(vector))
print(vector)

Vector length: 100
[-0.00713902  0.00124103 -0.00717672 -0.00224462  0.0037193   0.00583312
  0.00119818  0.00210273 -0.00411039  0.00722533 -0.00630704  0.00464722
 -0.00821997  0.00203647 -0.00497705 -0.00424769 -0.00310898  0.00565521
  0.0057984  -0.00497465  0.00077333 -0.00849578  0.00780981  0.00925729
 -0.00274233  0.00080022  0.00074665  0.00547788 -0.00860608  0.00058446
  0.00686942  0.00223159  0.00112468 -0.00932216  0.00848237 -0.00626413
 -0.00299237  0.00349379 -0.00077263  0.00141129  0.00178199 -0.0068289
 -0.00972481  0.00904058  0.00619805 -0.00691293  0.00340348  0.00020606
  0.00475375 -0.00711994  0.00402695  0.00434743  0.00995737 -0.00447374
 -0.00138926 -0.00731732 -0.00969783 -0.00908026 -0.00102275 -0.00650329
  0.00484973 -0.00616403  0.00251919  0.00073944 -0.00339215 -0.00097922
  0.00997913  0.00914589 -0.00446183  0.00908303 -0.00564176  0.00593092
 -0.00309722  0.00343175  0.00301723  0.00690046 -0.00237388  0.00877504
  0.00758943 -0.00954765 -0.00800

In [19]:
# Find Similar Words
word2vec_model.wv.most_similar("learning")

[('fun', 0.21617142856121063),
 ('i', 0.09291911125183105),
 ('powerful', 0.027057476341724396),
 ('love', 0.016134683042764664),
 ('machine', -0.01083916611969471),
 ('language', -0.027750369161367416),
 ('is', -0.05234673246741295),
 ('natural', -0.059876296669244766),
 ('processing', -0.111670583486557)]

In [20]:
word2vec_model.wv.similarity("language", "processing")

np.float32(-0.0446171)